name = "SimulacoesTemplate"
uuid = "80a31ae1-e083-42e8-a1fe-13e9bfb4f088"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br> and contributors"]
version = "0.2.1"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
Parameters = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
